# Use the official Node.js image
FROM node:lts

# Set the working directory
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY server/package*.json /app/server/

# Install dependencies
RUN npm install

# Copy the server code to /server
COPY server /app/server

# Copy the client code to /client
COPY client /app/client

# Expose the ports
EXPOSE 3000
EXPOSE 3001

# Command to run the application
CMD ["node", "server.mjs"]
