apiVersion: apps/v1
kind: Deployment
metadata:
  name: petri-io-server-deployment
  labels:
    app: petri-io-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petri-io-server
  template:
    metadata:
      labels:
        app: petri-io-server
    spec:
      containers:
        - name: server
          image: kqwq/petri-io-server:latest
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: 'development'
          command: ['node', 'server.mjs']
