apiVersion: v1
kind: Service
metadata:
  name: petri-io-server-service
spec:
  selector:
    app: petri-io-server
  ports:
    - protocol: TCP
      name: web-http
      port: 3000
      targetPort: 3000
    - protocol: TCP
      name: web-socket
      port: 3001
      targetPort: 3001
  type: NodePort
